name: Quickstart Flow Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Compile
        run: |
          ./mvnw install -Pquick -pl '!integration-test'

      - name: Create JsonB App and Run Tests
        run: |
          EXTENSION_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

          mvn io.quarkus:quarkus-maven-plugin:1.13.2.Final:create -Dextensions="resteasy,resteasy-jsonb" -DprojectGroupId=problem -DprojectArtifactId=quarkus-resteasy-problem-playground -DclassName="problem.HelloResource" -Dpath="/hello"
          sed 's/<dependencies>/<dependencies><dependency><groupId>com.tietoevry.quarkus<\/groupId><artifactId>quarkus-resteasy-problem<\/artifactId><version>'"$EXTENSION_VERSION"'<\/version><\/dependency>/g' quarkus-resteasy-problem-playground/pom.xml > quarkus-resteasy-problem-playground/pom2.xml

          ./mvnw verify -f quarkus-resteasy-problem-playground/pom2.xml